// <auto-generated />
using System;
using FamilyTreeApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FamilyTreeApi.Migrations
{
    [DbContext(typeof(FamilyTreeContext))]
    [Migration("20190622160652_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("FamilyTreeApi.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BirthYear");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<string>("Occupation");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("FamilyTreeApi.Models.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PersonId");

                    b.Property<int?>("RelatedToId");

                    b.Property<string>("Relationship");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("RelatedToId");

                    b.ToTable("Relation");
                });

            modelBuilder.Entity("FamilyTreeApi.Models.Relation", b =>
                {
                    b.HasOne("FamilyTreeApi.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("FamilyTreeApi.Models.Person", "RelatedTo")
                        .WithMany()
                        .HasForeignKey("RelatedToId");
                });
#pragma warning restore 612, 618
        }
    }
}
